### PR TITLE
deleted module "app"

### PR DESCRIPTION
**Pull request by giovannivelludo**

### CODE REVIEW

**Comment by CremaLuca** [comment]
Why removing app module? It's not useless, it's useful to test the library so that if you add something you can be 100% sure it works.
You can import just the smslibrary module in other projects and get rid of app module, but I think it's really not worth removing

**Comment by giovannivelludo** [comment]
The smslibrary module already has test and androidTest folders for testing

**Comment by CremaLuca** [comment]
You cannot test a successful send and delivery operation of a message on androidTest.

Also app is useful to use it as a demo app to show users how to use the library correctly (if there are operations like setups of singletons or things to be called in methods like onCreate and onDestroy), it's way easier to copy-paste from the demo than having an overall look on all interfaces and methods signatures.

**Comment by giovannivelludo** [comment]
I tought androidTest was meant for instrumented tests that use the Android framework and can run on real devices, and thus we could test sending and receiving SMS messages there. If you say that's not possible then I'll close this pull request. I didn't think about the fact that having a demo of the app could make it easier to implement it for other people.

**Pull request closed without merging**
